# You need to retrieve Machine information via gather_facts

- name: Netbox - Fact setup of vm
  setup:
  register: host_fact
  delegate_to: "{{ ip_dhcp }}"

- name: Netbox - Create a new device with the following
  netbox.netbox.netbox_device:
    netbox_url: "{{ netbox_url }}"
    netbox_token: "{{ netbox_user_token }}"
    data:
      name: "{{ inventory_hostname }}"
      device_type: "{{ host_fact.ansible_facts.ansible_virtualization_type }}"
      device_role: "{{ host_fact.ansible_facts.ansible_system_vendor }}"
      site: "{{ netbox_site }}"
      status: Active
      serial: "{{ host_fact.ansible_facts.ansible_product_serial }}"
      comments: "{{ vm.description }}"
    state: present
  delegate_to: localhost

- name: Netbox - Create the device interface
  netbox.netbox.netbox_device_interface:
    netbox_url: "{{ netbox_url }}"
    netbox_token: "{{ netbox_user_token }}"
    data:
      device: "{{ inventory_hostname }}"
      enabled: yes
      mac_address: "{{ host_fact.ansible_facts.ansible_default_ipv4.macaddress }}"
      mark_connected: yes
      mgmt_only: yes
      mtu: 1500
      type: 1000Base-t (1GE)
      name: "{{ host_fact.ansible_facts.ansible_default_ipv4.interface }}"
    state: present
  delegate_to: localhost

- name: Netbox - Store the address ipv4 with netmask
  set_fact: net_mask="{{ host_fact.ansible_facts.ansible_default_ipv4.network }}/{{ host_fact.ansible_facts.ansible_default_ipv4.netmask }}"
  delegate_to: "{{ ip_dhcp }}"

- name: Netbox - Calcul the real netmask of the network
  set_fact: net_prefix="{{ net_mask | ipaddr('net') }}"
  delegate_to: "{{ ip_dhcp }}"

- name: Netbox - Create a new ipv4 address for the device
  netbox.netbox.netbox_ip_address:
    netbox_url: "{{ netbox_url }}"
    netbox_token: "{{ netbox_user_token }}"
    data:
      prefix: "{{ net_prefix }}"
      assigned_object:
        device: "{{ inventory_hostname }}"
        name: "{{ host_fact.ansible_facts.ansible_default_ipv4.interface }}"
      status: Active
      dns_name: "{{ inventory_hostname }}"
      description: "{{ vm.description }}"
    state: present
  delegate_to: localhost